### ISSUE TITLE
Part list

### ISSUE THREAD

**Issue by Nervtoetertoeter** [Glitch752/LucidGlovesPCB#1]
Hi,
You posted a cart.png file showing your order - can you post a part list too?
Regards,
Nervtoetertoeter

**Comment by Glitch752** [comment]
This is a great call! I'm sorry that I neglected to add one.

I haven't fixed an oversight I found after receiving the PCB yet: the multiplexer pins are spaced for a different board than I'm using. I'll update the PCB and upload a part list when I have time this week.

Thanks!

**Comment by Nervtoetertoeter** [comment]
I noticed the problem with the multiplexer too, but i'm going to use double row pin headers to enlarge the layout of the multiplexer and simply cut the lower legs of the second row, so I don't need not reproduce the pcb or buy another multiplexer. Hope this sketch helps to understand how I solved this issue:
![multiplexer_extension](https://github.com/user-attachments/assets/d286c9d9-6417-4555-9c33-4dd3c3f63bdb)

**Comment by Glitch752** [comment]
Added in dbd3a09 and 772ac46. Sorry that took me so long!
